/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDiarioRouteImport } from './routes/_authenticated/diario'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedBibliotecaIndexRouteImport } from './routes/_authenticated/biblioteca.index'
import { Route as AuthenticatedBibliotecaSlugRouteImport } from './routes/_authenticated/biblioteca.$slug'
import { Route as AuthenticatedTrilhaIndexRouteImport } from './routes/_authenticated/trilha.index'
import { Route as AuthenticatedTrilhaDayRouteImport } from './routes/_authenticated/trilha.$day'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiarioRoute = AuthenticatedDiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBibliotecaIndexRoute =
  AuthenticatedBibliotecaIndexRouteImport.update({
    id: '/biblioteca/',
    path: '/biblioteca/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBibliotecaSlugRoute =
  AuthenticatedBibliotecaSlugRouteImport.update({
    id: '/biblioteca/$slug',
    path: '/biblioteca/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTrilhaIndexRoute =
  AuthenticatedTrilhaIndexRouteImport.update({
    id: '/trilha/',
    path: '/trilha/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTrilhaDayRoute = AuthenticatedTrilhaDayRouteImport.update({
  id: '/trilha/$day',
  path: '/trilha/$day',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/diario': typeof AuthenticatedDiarioRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/biblioteca/$slug': typeof AuthenticatedBibliotecaSlugRoute
  '/trilha/$day': typeof AuthenticatedTrilhaDayRoute
  '/biblioteca/': typeof AuthenticatedBibliotecaIndexRoute
  '/trilha/': typeof AuthenticatedTrilhaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/diario': typeof AuthenticatedDiarioRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/biblioteca/$slug': typeof AuthenticatedBibliotecaSlugRoute
  '/trilha/$day': typeof AuthenticatedTrilhaDayRoute
  '/biblioteca': typeof AuthenticatedBibliotecaIndexRoute
  '/trilha': typeof AuthenticatedTrilhaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/diario': typeof AuthenticatedDiarioRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/biblioteca/$slug': typeof AuthenticatedBibliotecaSlugRoute
  '/_authenticated/trilha/$day': typeof AuthenticatedTrilhaDayRoute
  '/_authenticated/biblioteca/': typeof AuthenticatedBibliotecaIndexRoute
  '/_authenticated/trilha/': typeof AuthenticatedTrilhaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/diario'
    | '/perfil'
    | '/biblioteca/$slug'
    | '/trilha/$day'
    | '/biblioteca/'
    | '/trilha/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/diario'
    | '/perfil'
    | '/biblioteca/$slug'
    | '/trilha/$day'
    | '/biblioteca'
    | '/trilha'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/diario'
    | '/_authenticated/perfil'
    | '/_authenticated/biblioteca/$slug'
    | '/_authenticated/trilha/$day'
    | '/_authenticated/biblioteca/'
    | '/_authenticated/trilha/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diario': {
      id: '/_authenticated/diario'
      path: '/diario'
      fullPath: '/diario'
      preLoaderRoute: typeof AuthenticatedDiarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/biblioteca/': {
      id: '/_authenticated/biblioteca/'
      path: '/biblioteca'
      fullPath: '/biblioteca/'
      preLoaderRoute: typeof AuthenticatedBibliotecaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/biblioteca/$slug': {
      id: '/_authenticated/biblioteca/$slug'
      path: '/biblioteca/$slug'
      fullPath: '/biblioteca/$slug'
      preLoaderRoute: typeof AuthenticatedBibliotecaSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trilha/': {
      id: '/_authenticated/trilha/'
      path: '/trilha'
      fullPath: '/trilha/'
      preLoaderRoute: typeof AuthenticatedTrilhaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trilha/$day': {
      id: '/_authenticated/trilha/$day'
      path: '/trilha/$day'
      fullPath: '/trilha/$day'
      preLoaderRoute: typeof AuthenticatedTrilhaDayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDiarioRoute: typeof AuthenticatedDiarioRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedBibliotecaSlugRoute: typeof AuthenticatedBibliotecaSlugRoute
  AuthenticatedTrilhaDayRoute: typeof AuthenticatedTrilhaDayRoute
  AuthenticatedBibliotecaIndexRoute: typeof AuthenticatedBibliotecaIndexRoute
  AuthenticatedTrilhaIndexRoute: typeof AuthenticatedTrilhaIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDiarioRoute: AuthenticatedDiarioRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedBibliotecaSlugRoute: AuthenticatedBibliotecaSlugRoute,
  AuthenticatedTrilhaDayRoute: AuthenticatedTrilhaDayRoute,
  AuthenticatedBibliotecaIndexRoute: AuthenticatedBibliotecaIndexRoute,
  AuthenticatedTrilhaIndexRoute: AuthenticatedTrilhaIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
